version: '3.9'
services:
  web:
    image: api-packages:latest
    container_name: container-api-packages
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /dev/null:/usr/src/app/.env